name: 'SecOps PR Checklist Action'
description: 'Scans PRs for security/privacy checklist violations and comments on PRs, updating Notion (mocked)'
author: 'Your Name'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs: {}

outputs: {}

branding:
  icon: 'shield'
  color: 'blue'

on:
  pull_request:
    types: [opened, synchronize, reopened] 