name: feature-flag-flag Clean-up Issue Handler

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  handle-feature-flag-cleanup:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'feature-flag-clean-up')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for creating a feature-flag clean-up issue! This will be reviewed by the team.'
            })
      
      # Add your custom steps here
      - name: Your custom action
        run: |
          echo "feature-flag clean-up issue created: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Created by: ${{ github.event.issue.user.login }}"